### ISSUE TITLE
UX Bug: How many stories am I seeing?

### ISSUE THREAD

**Issue by KristerV** [KristerV/HNSince#8]
from @hashbackup

> I thought HNS showed all stories since my last visit. 

This means more people will misunderstand this.

I assume it adds to the confusion, that HNS is showing 60 stories instead of the HN 30. Makes it seem like you're reading all.

I actually removed the More button just because I couldn't be bothered to implement it. BUT would be interesting to at least show how many stories are unseen. 

Pre-solution: display how many stories are left unseen. Then we can discuss if it makes sense to implement actual solution.

80/20 solution: implement the More button so you could actually read "all" of the stories. The only way for this to not take multiple days to implement is if there is no actual pagination, but the server sends like 90 stories (or whatever), but only shows 30.

**Comment by KristerV** [comment]
I just thought of something. I'm using hns every few days, you are using it multiple times a day. That means you may actually be seeing all stories.. in your case of we could remove the 1h minimum time window: then you could see exactly all stories..

**Comment by hashbackup** [comment]
That's how I expected it to work, whether I visited 3x per day or every 3 days.

**Comment by KristerV** [comment]
Perhaps some numbers will put this into perspective.

In the last 24h there were 1434 stories (I checked the db). Most of these have around 1 point. Do you really want to read all of 4500 if you've been gone for 3 days?

**Comment by hashbackup** [comment]
It seems like there are 2 things happening: filtering which stories to show and ordering the stories.  I'm not sure how filtering works.  I don't think it's by points, because I see stories with 0 points sometimes.  Maybe it's ordered by points with a max of M stories; I have no idea what M is.  It might be helpful to have a How It Works or "Confused?" link somewhere that explains how HNS works.

If I had been gone for 3 days and had 4500 stories queued, I guess I would want to see them ordered by descending points 50 or 100 at a time.  I just checked and it took me 75 seconds to scan through 30 new topics without reading any of them (I clicked the New link and wasn't interested in any).  So yeah, 4500 would take me 3 hours to scan if I didn't read any stories.

The other thing I just realized is that if a story was posted in the last hour and has 0 points, I may want to see it, whereas if it is 3 days old and has 0 points, I wouldn't want to see it.  I think you already do some filtering like this but don't know how it works.  Maybe exposing some of these knobs would help.

**Comment by KristerV** [comment]
Can you link a story with 0 points? Because that's a bug and should not happen, ever. All stories have 1 point by the author to start with. 0 means it's deleted or something, but I thought I took care of that.

There is no filtering. There's a 60 story max that is displayed. It's ordered by points.

3 days is one example, 30 days is another. The app must work with both ends of the frequency-of-visit spectrum.

Overall it seems to me that the real issue here is the 1h window. If it was 0 then frequent users could actually read all stories.

**Comment by KristerV** [comment]
> That's how I expected it to work, whether I visited 3x per day or every 3 days.
> […](#)
> On 1/15/21, Krister Viirsaar ***@***.***> wrote: I just thought of something. I'm using hns every few days, you are using it multiple times a day. That means you may actually be seeing all stories.. in your case of we could remove the 1h minimum time window: then you could see exactly all stories.. -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#8 (comment)](https://github.com/KristerV/HNSince/issues/8#issuecomment-760950407)

I'm wondering - what do you like about hnsince exactly? I mean if you want to read *all* stories then you can just read the original hn /new page?

**Comment by KristerV** [comment]
I'm asking, because I'm still trying to figure out a good solution. Currently I'm thinking perhaps take your "last story read" idea and max it our at 24h. So if I only visit once a week I still see the top posts, but the `last_story` is 24h old so I don't miss those. If I visit every hour, then basically I would be reading all of the stories that exist. My only problem with this is that the implementation doesn't seem fool-proof.

**Comment by KristerV** [comment]
I've implemented the more complicated solution and it seems to work.

So now the app logs the last story you saw and returns to that bookmark when you return. This only happens in a 48h timeframe (so if you visit more often than every other day) because if I visit once a week I don't want to read all stories, but only top ones.

I've also added a FAQ section to the bottom about this.

Closing, you can open a new issue if there are problems.
